apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: deploy-gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_HOSTNAME
          value: "keycloak"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Docker"